// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ScuolaNoRepo.Data;

#nullable disable

namespace ScuolaNoRepo.Migrations
{
    [DbContext(typeof(ScuolaContext))]
    [Migration("20251210083027_AggiungiDocenteECorso")]
    partial class AggiungiDocenteECorso
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("CorsoDocente", b =>
                {
                    b.Property<int>("CorsiId")
                        .HasColumnType("int");

                    b.Property<int>("DocentiId")
                        .HasColumnType("int");

                    b.HasKey("CorsiId", "DocentiId");

                    b.HasIndex("DocentiId");

                    b.ToTable("CorsoDocente");
                });

            modelBuilder.Entity("ScuolaNoRepo.Model.Corso", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("codiceId")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Corsi");
                });

            modelBuilder.Entity("ScuolaNoRepo.Model.Docente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Materia")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Docenti");
                });

            modelBuilder.Entity("ScuolaNoRepo.Model.Studente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Cognome")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int?>("CorsoId")
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("matricola")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("CorsoId");

                    b.ToTable("Studenti");
                });

            modelBuilder.Entity("CorsoDocente", b =>
                {
                    b.HasOne("ScuolaNoRepo.Model.Corso", null)
                        .WithMany()
                        .HasForeignKey("CorsiId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ScuolaNoRepo.Model.Docente", null)
                        .WithMany()
                        .HasForeignKey("DocentiId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ScuolaNoRepo.Model.Studente", b =>
                {
                    b.HasOne("ScuolaNoRepo.Model.Corso", null)
                        .WithMany("Studenti")
                        .HasForeignKey("CorsoId");
                });

            modelBuilder.Entity("ScuolaNoRepo.Model.Corso", b =>
                {
                    b.Navigation("Studenti");
                });
#pragma warning restore 612, 618
        }
    }
}
